export class KundliModel {
    lagna: string;
    combust: string;
    retrograte: string;
    navmansh: string;
    hora: string;
    drekkana: string;
    chaturthamansh: string;
    saptamamsha: string;
    dashamamsha: string;
    shashtiamsha: string;
    khavedamsha: string;
    akshvedamsha: string;
    vimshamsha: string;
    saptavimshamsha: string;
    chaturvimshamsha: string;
    dwadashamamsha: string;
    trimshamsha: string;
    shodashamsha: string;
    moon: any;
    kpCusp: string;
    kpayan: string;
    fortuna: string;
    planetDegree: string;
    ayan: string;
    ashtakvargar1: string;
    ashtakvargar2: string;
    ashtakvargar3: string;
    ashtakvargar4: string;
    ashtakvargar5: string;
    ashtakvargar6: string;
    ashtakvargar7: string;
    ashtakvargar8: string;
    ashtakvargar9: string;
    ashtakvargar10: string;
    ashtakvargar11: string;
    ashtakvargar12: string;
    paksha: string;
    tithi: string;
    nakshatra: string;
    hinduWeekDay: string;
    englishWeekDay: string;
    yoga: string;
    karan: string;
    sunRiseTime: string;
    sunSetTime: string;
    prastharashtakvarga: any;
    paya: string;
    varna: string;
    yoni: string;
    gana: string;
    vasya: string;
    nadi: string;
    balanceOfDasha: string;
    lagnaA: string;
    lagnaLord: string;
    rasi: string;
    rasiLord: string;
    nakshatraPada: string;
    nakshatraLord: string;
    julianDay: string;
    sunSignIndian: string;
    sunSignWestern: string;
    ayanamsa: string;
    ayanamsaName: string;
    obliquity: string;
    sideralTime: string;
    planetSignification1: string;
    planetSignification2: string;
    planetSignification3: string;
    planetSignification4: string;
    planetSignification5: string;
    planetSignification6: string;
    planetSignification7: string;
    planetSignification8: string;
    planetSignification9: string;
    rpdayLord: string;

    constructor(init?: Partial<KundliModel>) {
        this.lagna = "";
        this.combust = "";
        this.retrograte = "";
        this.navmansh = "";
        this.hora = "";
        this.drekkana = "";
        this.chaturthamansh = "";
        this.saptamamsha = "";
        this.dashamamsha = "";
        this.shashtiamsha = "";
        this.khavedamsha = "";
        this.akshvedamsha = "";
        this.vimshamsha = "";
        this.saptavimshamsha = "";
        this.chaturvimshamsha = "";
        this.dwadashamamsha = "";
        this.trimshamsha = "";
        this.shodashamsha = "";
        this.moon = null;
        this.kpCusp = "";
        this.kpayan = "";
        this.fortuna = "";
        this.planetDegree = "";
        this.ayan = "";
        this.ashtakvargar1 = "";
        this.ashtakvargar2 = "";
        this.ashtakvargar3 = "";
        this.ashtakvargar4 = "";
        this.ashtakvargar5 = "";
        this.ashtakvargar6 = "";
        this.ashtakvargar7 = "";
        this.ashtakvargar8 = "";
        this.ashtakvargar9 = "";
        this.ashtakvargar10 = "";
        this.ashtakvargar11 = "";
        this.ashtakvargar12 = "";
        this.paksha = "";
        this.tithi = "";
        this.nakshatra = "";
        this.hinduWeekDay = "";
        this.englishWeekDay = "";
        this.yoga = "";
        this.karan = "";
        this.sunRiseTime = "";
        this.sunSetTime = "";
        this.prastharashtakvarga = null;
        this.paya = "";
        this.varna = "";
        this.yoni = "";
        this.gana = "";
        this.vasya = "";
        this.nadi = "";
        this.balanceOfDasha = "";
        this.lagnaA = "";
        this.lagnaLord = "";
        this.rasi = "";
        this.rasiLord = "";
        this.nakshatraPada = "";
        this.nakshatraLord = "";
        this.julianDay = "";
        this.sunSignIndian = "";
        this.sunSignWestern = "";
        this.ayanamsa = "";
        this.ayanamsaName = "";
        this.obliquity = "";
        this.sideralTime = "";
        this.planetSignification1 = "";
        this.planetSignification2 = "";
        this.planetSignification3 = "";
        this.planetSignification4 = "";
        this.planetSignification5 = "";
        this.planetSignification6 = "";
        this.planetSignification7 = "";
        this.planetSignification8 = "";
        this.planetSignification9 = "";
        this.rpdayLord = "";
        Object.assign(this, init);
    }
}
